### ISSUE TITLE
Nix support

### ISSUE THREAD

**Issue by domenkozar** [haskell/hie-bios#25]
I'd like to propose Nix support.

By default, it would use `shell.nix` to enter the environment.

An example default configuration (mostly inspired by stack):

```yaml
nix:
  enable: true
  shell-file: shell.nix
```
