### ISSUE TITLE
bios cradle: Allow `with-ghc` to be specified programmatically

### ISSUE THREAD

**Issue by sol** [haskell/hie-bios#401]
Similar to how you can specify `dependencies` programmatically by writing to `$HIE_BIOS_DEPS` I would like to be able to specify `with-ghc` programmatically by writing to e.g. `$HIE_BIOS_WITH_GHC`.

**Comment by fendor** [comment]
Unfortunately, what you are proposing is too late for HLS. The GHC version is cradle wide, but what you are describing is per `Component`. See https://github.com/haskell/hie-bios/pull/274 for a discussion.

**Comment by sol** [comment]
@fendor just to make sure that I understand your point correctly, are you saying that instead of

```yaml
cradle:
  bios:
    shell: ... # determine options and path to ghc
```

we would need something like

```yaml
cradle:
  bios:
    shell: ... # determine options
    with-ghc:
      shell: ... # determine path to ghc
```
(That is, we need the user to specify two separate commands, one for options, and one for the GHC version.).

Is that where you are heading at?
